"""add_all_rag_tables_and_indexes

Revision ID: 25c37890e8be
Revises: 951b6c8ad312
Create Date: 2025-09-27 17:36:17.929390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c37890e8be'
down_revision = '951b6c8ad312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable pgvector extension FIRST
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    # ... all auto-generated CREATE TABLE commands ...
    # ### end Alembic commands ###
    
    # Create vector indexes AFTER tables exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS documents_embedding_idx 
        ON documents 
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100);
    """)
    
    op.create_index('idx_documents_user_type', 'documents', ['user_id', 'doc_type'])
    op.create_index('idx_documents_source', 'documents', ['doc_type', 'source_id'])
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_documents_metadata 
        ON documents USING gin(metadata);
    """)


def downgrade() -> None:
    # Drop indexes first
    op.execute('DROP INDEX IF EXISTS idx_documents_metadata;')
    op.drop_index('idx_documents_source', table_name='documents')
    op.drop_index('idx_documents_user_type', table_name='documents')
    op.execute('DROP INDEX IF EXISTS documents_embedding_idx;')
    
    # ### commands auto generated by Alembic - please adjust! ###
    # ... all auto-generated DROP TABLE commands ...
    # ### end Alembic commands ###