"""Initial schema with users and OAuth

Revision ID: 951b6c8ad312
Revises: 62c5626e7c9f
Create Date: 2025-09-27 07:40:05.723270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b6c8ad312'
down_revision = '62c5626e7c9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###