"""add_rag_models_and_pgvector

Revision ID: a34a10da60af
Revises: 951b6c8ad312
Create Date: 2025-09-27 XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector  # Add this import

# revision identifiers, used by Alembic.
revision = 'a34a10da60af'
down_revision = '951b6c8ad312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable pgvector extension FIRST - before any table creation
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    # ... rest of auto-generated code stays exactly the same ...
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ... rest of auto-generated code stays exactly the same ...
    # ### end Alembic commands ###
    
    # Optionally drop extension at the very end
    # op.execute('DROP EXTENSION IF EXISTS vector')