"""add_rag_models_and_pgvector

Revision ID: a34a10da60af
Revises: 951b6c8ad312
Create Date: 2025-09-27 17:02:07.218101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34a10da60af'
down_revision = '951b6c8ad312'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###